#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep 'HDMI-0 connected'; then
	#xrandr --output eDP-1 --auto --output HDMI-1-0 --auto --left-of eDP-1 --primary
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --output eDP-1-1 --auto --output HDMI-0 --auto --left-of eDP-1-1 --primary 
	bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0
	bspc monitor eDP-1-1 -d Desktop
else
	#xrandr --output eDP-1 --auto
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xrandr --auto
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer action2 resize_side
bspc config pointer_action2 rezize_corner

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


$HOME/.config/polybar/launch.sh &
